# Generated by Django 5.2.17 on 2026-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to sell without tracking stock.', null=True),
        ),
    ]
