# Generated by Django 5.2.17 on 2026-09-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, help_text='Absolute URL, or a site-relative path such as /media/products/name.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(help_text='Absolute URL, or a site-relative path such as /media/products/name.jpg', max_length=500),
        ),
    ]
