# Generated by Django 5.2.17 on 2026-09-23 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def give_existing_orders_unique_tokens(apps, schema_editor):
    """Give every pre-existing order its own public token.

    Adding a column with a callable default applies that one value to every
    existing row, which would mean a single leaked token opened *every* legacy
    order. This walks the rows and assigns a distinct token to each.
    """
    Order = apps.get_model("commerce", "Order")
    for order in Order.objects.all().iterator():
        order.public_token = uuid.uuid4()
        order.save(update_fields=["public_token"])


def give_duplicate_carts_distinct_keys(apps, schema_editor):
    """Rename duplicate baskets before the unique index is created.

    The previous code allowed two rows to share a ``session_key``; without this
    the unique constraint would fail on a live database.
    """
    Cart = apps.get_model("commerce", "Cart")
    seen = set()
    for cart in Cart.objects.order_by("id").iterator():
        if cart.session_key in seen:
            cart.session_key = f"dup{cart.pk}_{uuid.uuid4().hex[:24]}"
            cart.save(update_fields=["session_key"])
        seen.add(cart.session_key)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_stock_quantity'),
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]


    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(
            give_existing_orders_unique_tokens,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='order',
            name='stock_reduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product'),
        ),
        migrations.RunPython(
            give_duplicate_carts_distinct_keys,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
